### ISSUE TITLE
Order status pending when payment cancelled and later authorized

### ISSUE THREAD

**Issue by evs-xsarus** [Adyen/adyen-magento2#488]
**Magento version**: 2.2.7
**Plugin version**: 3.0.0
**Description**

I have an order with this payment history:

* 25 jul. 2019 10:53:37 Pending Customer Notified / Order created
* 25 jul. 2019 10:55:13 Customer Not Notified / Order status is set to 'Canceled' and order items are cancelled.
    > Adyen Result URL response: 
    > authResult: CANCELLED 
    > pspReference: 
    > paymentMethod: ideal
* 25 jul. 2019 11:00:05 Canceled Customer Not Notified / Order status is set to Pending but order items stay cancelled.
    > Adyen HTTP Notification(s): 
    > eventCode: AUTHORISATION 
    > pspReference: xxxxxxxxxxxxxxxxx 
    > paymentMethod: ideal 
    > success: true 
    > reason:ideal
* 25 jul. 2019 11:00:05 Pending Customer Not Notified / Order stays on pending but will never get an invoice because the items are still cancelled.
 > Payment is authorised waiting for capture

I believe that the order items must also be uncancelled by this Adyenplugin since it's weird to have a pending order with only cancelled items.

**Comment by ryanpalmerweb** [comment]
Hi Adyen,

We've noticed this problem in our stores aswell, we are using plugin version 4.0.1

When the customer returns from a failed payment, it looks like the order ID is not being changed, and they are being allowed to go back to Adyen to make a second attempt.

As the original order is cancelled, the success notification is unable to change the order to a processing state.

I would expect the behaviour here to be that a new order number was issued, or that the module undoes the cancellation.

I've attached the access log so that you can see the customer flow, with any identifying information removed.

> (customer ip address removed) - - [21/Aug/2019:17:03:32 +0100] "GET /adyen/process/redirect/ HTTP/2.0" 200 1998 "https://www.ourwebsite.co.uk/checkout/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:03:47 +0100] "GET /adyen/process/result?authResult=CANCELLED&merchantReference=9000018715&merchantSig=(merchant sig removed)%3D&paymentMethod=amex&shopperLocale=en_GB&skinCode=(skin code removed) HTTP/2.0" 499 0 "https://live.adyen.com/hpp/details.shtml" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:04:26 +0100] "GET /adyen/process/result?authResult=CANCELLED&merchantReference=9000018715&merchantSig=(merchant sig removed)%3D&paymentMethod=amex&shopperLocale=en_GB&skinCode=(skin code removed) HTTP/2.0" 499 0 "https://live.adyen.com/hpp/details.shtml" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:04:29 +0100] "GET /adyen/process/result?authResult=CANCELLED&merchantReference=9000018715&merchantSig=(merchant sig removed)%3D&paymentMethod=amex&shopperLocale=en_GB&skinCode=(skin code removed) HTTP/2.0" 499 0 "https://live.adyen.com/hpp/details.shtml" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:04:29 +0100] "GET /checkout/ HTTP/2.0" 499 0 "https://www.ourwebsite.co.uk/checkout/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:04:31 +0100] "GET /checkout/ HTTP/2.0" 499 0 "https://www.ourwebsite.co.uk/checkout/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:04:31 +0100] "GET /checkout/ HTTP/2.0" 499 0 "https://www.ourwebsite.co.uk/checkout/cart/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:04:35 +0100] "GET /checkout/cart/ HTTP/2.0" 499 0 "https://www.ourwebsite.co.uk/electric-roller-blind-issac-charcoal/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:07:19 +0100] "GET /adyen/process/result?authResult=AUTHORISED&merchantReference=9000018715&merchantSig=(removed)%3D&paymentMethod=amex&pspReference=1515664036371234&shopperLocale=en_GB&skinCode=(skin code removed) HTTP/2.0" 302 860 "https://live.adyen.com/hpp/completeCard.shtml" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

> (customer ip address removed) - - [21/Aug/2019:17:07:20 +0100] "GET /checkout/onepage/success/?utm_nooverride=1 HTTP/2.0" 200 19576 "https://live.adyen.com/hpp/completeCard.shtml" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

We are in the process of moving from the HPP to API by updating the Adyen module, so it might be that this issue is resolved by the changed customer flow. 

Thanks,
Ryan

**Comment by JeroenVanLeusden** [comment]
@cyattilakiss You have an update? We see this regularly with v5 of this module.

**Comment by cyattilakiss** [comment]
Hi @evs-xsarus , @ryanpalmerweb 

The issue that you were describing should be fixed after the version 5.0.0, we moved from our custom exposed API to handle the payment and the order back to the Magento provided process.
Could you please verify that you still experience this issue?

@JeroenVanLeusden the issue you mention also should be fixed in one of the latest versions: https://github.com/Adyen/adyen-magento2/blob/5.1.0/Model/Cron.php#L410-L421
Could you please verify that you still experience this issue?

I will keep this ticket open until your feedback.

Have a great day!
Best,
Attila
Adyen

**Comment by evs-xsarus** [comment]
Will be able to monitor this from coming monday.

**Comment by atty31** [comment]
Hi, I am facing the same issue. See my pic:
![Screenshot (14)](https://user-images.githubusercontent.com/3530315/73929573-559fee80-48d5-11ea-8bd7-fe9769d195a9.png)

on Magento ver. 2.3.3 and the module version is 5.0.1 .

**Comment by cyattilakiss** [comment]
Hi @evs-xsarus , @ryanpalmerweb , @JeroenVanLeusden , @atty31 

Thank you all for the input. We created a fix #679 for this issue. After investigating we found that redirect payment methods can redirect the shopper back to the store with cancelled status even though the payment was authorised or was still pending. In the plugin we were cancelling the order to make the reserved item available again in the stock as fast as possible. Because of the redirect resultCode inconsistency now we rely on the notifications to cancel (or authorise) the order.

This patch will be released in 6.x.x but since the code change is compact enough you can patch your current version yourself just to validate and proceed faster.

Let me know if you have further questions.

Best,
Attila
Adyen

**Comment by Beagon** [comment]
Hi,

I seem to still encounter this issue. I've seen this on 2 yesterday one if which was a PayPal order and the other one iDeal. We're running version 6.4.0 but are upgrading to 6.6.0 but I don't feel like this has to do with 6.4.0 since this should be fixed in 6.2.

Sincerely,

Robin

**Comment by cyattilakiss** [comment]
Hi @Beagon ,

I've just answered in the ticket: #717 

Best,
Attila
