### ISSUE TITLE
Adyen payment icons missing on checkout

### ISSUE THREAD

**Issue by kavindu** [Adyen/adyen-magento2#66]
On  Hosted Payment Page (HPP) integration enable with advanced setting "Payment method selection on Adyen Hosted Payment Page (HPP)" - No,

In checkout payment icons not display properly,

generated image asset url is - http://domain/pub/static/frontend/_view/en_US/Adyen_Payment/images/logos/diners.png

it need to be something like -
pub/static/frontend/Magento/luma/en_US/Adyen_Payment/images/logos/diners.png

**Comment by rikterbeek** [comment]
Hi @kavindu,

Strange It should not generate any icon image at all. Are you on our latest version ?
I will add a default image if the setting "Payment method render method" is set to "Logo + Title".

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @kavindu,

The above commit should show the icon now if you have setting "Payment method render method" is set to "Logo + Title".

Regards,
Rik
Adyen

**Comment by kavindu** [comment]
Hi riterbeek,

i'm using Magento ver. 2.1.0 with adyen 1.4.5.
i have try with single magento as well as multiple magento stores. 

It seams with rest request, need to pass following two parameter "theme" and "themeModel"  for create asset image properly, 

/vendor/adyen/module-payment/Helper/PaymentMethods.php , Line 216

**Comment by kavindu** [comment]
Following fix worked for us. additionally pass  theme parameter as  'Magento/blank'

Helper/PaymentMethods.php , Line 216

$params = array_merge(['area' => 'frontend', 'theme' => 'Magento/blank', '_secure' => $this->_request->isSecure()], $params);

**Comment by rikterbeek** [comment]
Hi @kavindu,

I am not sure we need to provide this because it can be dynamic. You have an option "Base URL for Static View Files" so maybe you need this to use magento/blank

I could not reproduce it my image is linked to: 
http://2.1.0.magento.adyenshop.nl/pub/static/frontend/Magento/luma/en_US/Adyen_Payment/images/logos/diners.png
and it worked.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi,

I can see that we use findRelativeSourceFilePath() method of magento that is now deprecated. There is a note that this method will not work If custom vendor directory is outside the Magento root. Is this in your situation the case ? We will try to figure out what new method magento has to solve this.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi,

Could you check if above is a working solution for you ?

Regards,
Rik
Adyen

**Comment by kavindu** [comment]
Hi Rikterbeek,

above fix not work for  adyen HPP section. 
it seams with rest request, create asset properly we need to pass default theme parameter.

Currently pass following parameters only ,  
$params = array_merge(['area' => 'frontend', '_secure' => $this->_request->isSecure()], $params);

we need to pass theme parameter as 'Magento/blank' with REST requests. theme fallback also worked for us once include theme this parameters

**Comment by rikterbeek** [comment]
Hi @kavindu,

That fallback mechanisme should be already implemented in the core of magento see:
https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/View/Asset/Source.php#L186-L220
What version of M2 are you on ?

Regards,
Rik
Adyen

**Comment by kavindu** [comment]
i have test it with Community 2.1.0.
we got this issue with enable adyen hpp
setting "Payment method selection on Adyen Hosted Payment Page (HPP)" - No,

**Comment by rikterbeek** [comment]
Hi @kavandu

Could you debug the magento core fallback in the magento core system see link in previous reaction. If i look in that method code they already build in a fallback but for reason that is not triggered. I think this is a bug on magento.

Regards,
Rik
Adyen

**Comment by kavindu** [comment]
@rikterbeek ,

it seams not a magento bug, we use REST request for load HPP adyen payment methods, i think for that we need to pass, what is the are we referring, do we need to process as secure request or not and the base theme use.
 
Example:-
['area' => 'frontend', '_secure' => $this->_request->isSecure(), **_'theme' => 'Magento/blank',_**]

**Comment by rikterbeek** [comment]
Hi @kavindu,

If you look deeper in the code you can see that magento should set the fallback parameters.
https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/View/Asset/Source.php#L197

This is triggered because we set the asset through https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/View/Asset/Repository.php#L210-L216

You can see that we do not provide the parameters area and locale but if you look here:
https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/View/Asset/Repository.php#L203

you can see that magento should set the parameters to the default:
https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/View/Asset/Repository.php#L130-L167
Could you debug why this is not the case in your environment ?

Regards,
Rik
Adyen

**Comment by kweij** [comment]
I run into the same problem since the upgrade from Magento 2.0.x to Magento 2.1.0.

I'm still debugging, but have not found the core of the problem yet. Eventually the theme-part of the path (`$asset->context->theme`) contains the value `\Magento\Framework\View\DesignInterface::PUBLIC_VIEW_DIR` which is `"_view"`. This ends up in the interface.

I'm using a custom theme that extends Magento/blank.

**Comment by TommyKolkman** [comment]
I've got the same problem as @kweij - from 2.0.7 to 2.1.1. Custom theme that extends blank as well. Anything found something out yet or has a quick fix?

**Comment by kweij** [comment]
I haven't found the root of the problem, but I would like to tag this as a Bug as it doesn't seem to work out of the box for a custom theme (that's not `en_US`)

**Comment by TommyKolkman** [comment]
This happened to me again on Magento 2.1.3 and Adyen 2.0.0.

**Comment by kweij** [comment]
Are there any updates on this issue? Because the images are still not showing

**Comment by rikterbeek** [comment]
Hi,

No updates yet. It looks like the fallback mechanisme is not working correctly in the core. Would be great if you could debug the core code and check why the fallback is not triggered correctly.

I don't like adding the theme in the call because then there is no way to overwrite the logos in your custom theme.

Regards,

**Comment by jbalca** [comment]
Hi @rikterbeek ,

I have the same problem. We are running Magento 2 CE 2.1.3. Any plans to fix this? It seems the problem is going on for some time now...

Regards,
José

**Comment by jbalca** [comment]
Hi @rikterbeek,

I've debug this a lit bit and I believe the program is this:
1. The request for available payment methods, for a given country and quote_id, is being made using the API function getPaymentMethods (Adyen\Payment\Api\AdyenPaymentMethodManagementInterface).
2. Using the API is telling Magento to assume app(area) to be 'webrest_api', instead of 'frontend'.
3. The template is not initialise in this scenario... and that's why the magento fallback is not being triggered.

I think the best way to fix this is to request the available payment methods using a controller instead of the API function.

Regards,
José

**Comment by rikterbeek** [comment]
Hi @jbalca,

Controller is not possible because we retrieve the payment methods based on the country that is selected in the shipping address field. Can you check if this issue still occur in 2.1.6 ?

Regards,
Rik
Adyen

**Comment by jbalca** [comment]
@rikterbeek At the moment we're running Magento version 2.1.3.

What I can tell you is that the problem starts here, because `'frontend' != 'webrest_api'`:
https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/lib/internal/Magento/Framework/View/Asset/Repository.php#L144

And within the "normal flow" this line it's executed instead, and in this case `themeModel` is already initialized:
https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/lib/internal/Magento/Framework/View/Asset/Repository.php#L154

Regards,
José

**Comment by rikterbeek** [comment]
Hi @jbalca 

It looks like it is a core issue. Not sure if this is fixed in later versions could be something we will need to investigate. Could you check if this quickfix solve the issue:

$params = array_merge(['area' => 'frontend', 'theme' => 'Magento/blank', '_secure' => $this->_request->isSecure()], $params);

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @jbalca,

This issue is resolved in the 2.1.6 version of Magento.

Regards,
Rik
Adyen

**Comment by jbalca** [comment]
Hi @rikterbeek ,

We're using Magento CE 2.1.3 but we have plans to upgrade very soon. I'll give you some feedback after that.

Regards,
José

**Comment by OnTapKristjan** [comment]
Hi @rikterbeek , in case the extension claims to be compatible with anything earlier than 2.1.6 - I don't see the point in closing off this ticket.
This is and will remain a problem for us as well until either us or somebody else fixes this.

I know that almost everything could be blamed on Magento these days, but it does not change the fact that extension only fully works on 2.1.6

Would be good if we can get some feedback on this because it's blocking our launch.

Regards,
Kristjan

**Comment by kuwiano** [comment]
Hi everyone, we are using Magento version 2.1.6 and version 2.0.6 of your plugin and this still happens to us. With HPP payments no logo is displayed and the generate path is:

static/version1500970041/frontend/_view/fr_FR/Adyen_Payment/images/logos/cartebancaire.png

**Comment by lancergr** [comment]
Hi @OnTapKristjan @jbalca 

This should be fixed with #158 

Best Regards,
Giorgos
Adyen
